mainprefix: "i!"
defaultjoinmessage: "**{user} Joined Invited By {Inviter} (Invites: {inv})**"
defaultleavemessage: "**{user} Left, Invited by {inviter}**"
token: "NzQ3NDkwOTc0MjQyMTc3MDc1.X0PpNw.ilAGbGBWVXVKLxuGVeS84rpv0eU"
color: "BLUE"
